type Comment {
  id: ID!
  text: String!
  author: User!
  post: Post
  createdAt: String!
  updatedAt: String!
}

type CommentSubscriptionPayload {
  mutation: MutationType!
  node: Comment
}

type Query {
  comments(
    first: Int
    skip: Int
    after: String
    orderBy: CommentOrderByInput
  ): [Comment!]!
}

type Mutation {
  createComment(data: CreateCommentInput!): Comment!
  deleteComment(id: ID!): Comment!
  updateComment(id: ID!, data: UpdateCommentInput!): Comment!
}

type Subscription {
  comment(postId: ID!): CommentSubscriptionPayload!
}

input CreateCommentInput {
  text: String!
  post: ID!
}

input UpdateCommentInput {
  text: String
}
